### ISSUE TITLE
setVisibleColumns in detail table

### ISSUE THREAD

**Issue by mortoza** [tyl/field-binder#4]
HI
I am trying to display only selected columns in detail table but getting exception below. I have checked the field names in Address table through. Any clue?

My code is:
listTable.setVisibleColumns("id","street", "zipCode", "city", "state");

Caused by: java.lang.IllegalArgumentException: Ids must exist in the Container or as a generated column, missing id: id
    at com.vaadin.ui.Table.setVisibleColumns(Table.java:660)
    at org.tylproject.vaadin.addon.fieldbinder.ListTable.setVisibleColumns(ListTable.java:97)
    at com.my.entity.PersonAddressFieldBinderView.initComponent(PersonAddressFieldBinderView.java:112)
    ... 70 more

**Comment by evacchi** [comment]
Can you share the source code that causes the error?

**Comment by mortoza** [comment]
Here is the code

``` java
@PostConstruct
public void initComponent() {
    container = new FilterableListContainer<>(Person2.class);
    binder = new FieldBinder<>(Person2.class, container);            
    initFieldBinderListener();
    ListTable<Address2> listTable = binder.buildListOf(Address2.class, "addressList");
    listTable.setVisibleColumns("id","street", "zipCode", "city", "state");
    mainLayout = new MVerticalLayout(
            new ButtonBar(binder.getNavigation().withDefaultBehavior()),
            new MFormLayout(
                    binder.build("id"),
                    binder.build("firstName"),
                    binder.build("middleName"),
                    binder.build("lastName"),
                    binder.build("birthDate"),
                    binder.build("age"),
                    new NavigationLabel(binder.getNavigation())
            ).withFullWidth().withMargin(true),
            listTable
    ).withFullWidth().withMargin(true);

    addComponent(mainLayout);

}

```

it is occurring from this line:
          `listTable.setVisibleColumns("id","street", "zipCode", "city", "state");`

**Comment by evacchi** [comment]
can you try moving that line at the end of the method?

**Comment by mortoza** [comment]
I tried it putting that line (listTable.setVisibleColumns("id","street", "zipCode", "city", "state");),
just before the last line (addComponent(mainLayout);)

same outcome.

**Comment by evacchi** [comment]
this is a bug due to the underlying `Table` widget, which raises this error if the `setVisibleColumn()` is invoked before  `Table.setContainerDataSource()` has been invoked. As a workaround, you might want to try doing the following:

``` java
   ...
    ).withFullWidth().withMargin(true);

    // force the navigator to fetch the first item and feed it to the fieldbinder
    // feeding in turn the listTable's container
    binder.getNavigation().first();
    listTable.setVisibleColumns("id","street", "zipCode", "city", "state");
    addComponent(mainLayout);
```

I will fix this in the next version by invoking the setVisibleColumn() method only when the underlying table's internal state is consistent

**Comment by mortoza** [comment]
Tried but having the same exception

Caused by: java.lang.IllegalArgumentException: Ids must exist in the Container or as a generated column, missing id: id
    at com.vaadin.ui.Table.setVisibleColumns(Table.java:660)
    at org.tylproject.vaadin.addon.fieldbinder.ListTable.setVisibleColumns(ListTable.java:97)
    at com.my.entity.PersonAddressFieldBinderView.initComponent(PersonAddressFieldBinderView.java:111)
    ... 70 more

**Comment by evacchi** [comment]
If the container supports it, you might try to use `addContainerProperty()` beforehand.

**Comment by mortoza** [comment]
Thanks.

When are you going to release version 1.2? I am eager to try that!

regards
Mortoza

**Comment by evacchi** [comment]
1.2 is out, have fun!

**Comment by mortoza** [comment]
Hi
I am still getting this error message even I am using 1.2 version.

**Comment by evacchi** [comment]
ok I'll check it again and release a hotfix if I can reproduce the issue.

**Comment by evacchi** [comment]
v1.2.2 should fix this issue

**Comment by mortoza** [comment]
Hi
I am now using version 1.2.2. It works when I use JPAContainer but not FilterableListContainer that I used in my previous example shared with you. However. when I try to save the entries, getting following exceptions-

``` java
Severe:   com.vaadin.event.ListenerMethod$MethodException: Invocation of method onCommit in org.tylproject.vaadin.addon.fieldbinder.behavior.BehaviorFacade failed.
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:528)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at org.tylproject.vaadin.addon.datanav.BasicDataNavigation.commit(BasicDataNavigation.java:216)
    at org.tylproject.vaadin.addon.datanav.CrudButtonBar$4.buttonClick(CrudButtonBar.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:198)
    at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:161)
    at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:979)
    at com.vaadin.ui.Button.fireClick(Button.java:393)
    at com.vaadin.ui.Button$1.click(Button.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:168)
    at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:118)
    at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:287)
    at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:180)
    at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:93)
    at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:41)
    at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1406)
    at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:305)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
    at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
    at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
    at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
    at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
    at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
    at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
    at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
    at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
    at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
    at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
    at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
    at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
    at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: 
Exception Description: Cannot use an EntityTransaction while using JTA.
    at org.eclipse.persistence.internal.jpa.transaction.JTATransactionWrapper.getTransaction(JTATransactionWrapper.java:73)
    at org.eclipse.persistence.internal.jpa.EntityManagerImpl.getTransaction(EntityManagerImpl.java:1311)
    at com.vaadin.addon.jpacontainer.provider.MutableLocalEntityProvider.runInTransaction(MutableLocalEntityProvider.java:111)
    at com.vaadin.addon.jpacontainer.provider.MutableLocalEntityProvider.addEntity(MutableLocalEntityProvider.java:137)
    at com.vaadin.addon.jpacontainer.provider.CachingMutableLocalEntityProvider.addEntity(CachingMutableLocalEntityProvider.java:164)
    at com.vaadin.addon.jpacontainer.JPAContainer.addEntity(JPAContainer.java:1113)
    at org.tylproject.vaadin.addon.fieldbinder.behavior.containers.jpacontainer.JPAContainerCrud.onCommit(JPAContainerCrud.java:39)
    at org.tylproject.vaadin.addon.fieldbinder.behavior.BehaviorFacade.onCommit(BehaviorFacade.java:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:508)
    ... 55 more
```

Here is my code to save data:

```
        @Override
        public void afterCommit(AfterCommit.Event event) {
            if (binder.getBindingPropertyIds() == null) {
                facade.create(binder.getBeanDataSource());
            } else {
                facade.edit(binder.getBeanDataSource());
            }
        }
```

If I replace facade with container, I still get exception

Any thoughts?

**Comment by evacchi** [comment]
well, the stack trace you are getting is quite explicit about it

```
    Exception Description: Cannot use an EntityTransaction while using JTA.
```

So, I guess you should check your JPA/JTA/GlassFish configuration :)

This is issue is also unrelated both to the `setVisibleColumn()` and --- it seems --- to FieldBinder altogether, since it appears to be a JPA configuration issue. Thus, I am closing this issue and I would advise to look for help on Vaadin's forums.

Thanks for your continued interest in FieldBinder, and, please, do not hesitate to open a new issue if you are sure it is related to our add-on !
